name: Golf Booking
on:
  schedule:
    - cron: "59 3 * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install selenium webdriver-manager

    - name: Run bot
  env:
    GOLF_USER: ${{ secrets.GOLF_USER }}
    GOLF_PASS: ${{ secrets.GOLF_PASS }}
      run: python golf_bot.py
